
# html lang
language: en

# main menu navigation
menu:
  Home: /

highlight:
  enable: false

scripts:
- /js/attraction.js
- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.46.0/codemirror.min.js

styles:
- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.46.0/codemirror.min.css
- https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.46.0/theme/seti.min.css
